### ISSUE TITLE
Is it possible to combine mods like the "Create" mod with Veil?

### ISSUE THREAD

**Issue by MikesQuest** [FoundryMC/Veil#46]
I recently made custom armor with a built-in flashlight using Veil. This works perfectly, however I tried to combine this custom mod I'm working on with the Create mod, but it seems that when I activate the shaders to allow the arealight to work, the game crashes when I place some blocks/items from the Create mod which use **Flywheel** (which I believe is a separate rendering engine).

I'm currently creating the mod for Minecraft 1.20.1 in Forge.

Some logs:
```
net.minecraft.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:64) ~[forge-1.20.1-47.3.12_mapped_parchment_2023.06.26-1.20.1.jar%23191!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:veil.forge.mixins.json:client.deferred.ModelBlockRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
```

```
Minecraft Crash Report
Shall we play a game?

Time: 2024-12-20 11:00:47
Description: Tesselating block model

java.lang.UnsupportedOperationException: ShadeSeparatingVertexConsumer only supports putBulkData!
```

Suspected Mods:

	Flywheel (flywheel), Version: 0.6.11-13
		Issue tracker URL: https://github.com/Jozufozu/Flywheel/issues
		at TRANSFORMER/flywheel@0.6.11-13/com.jozufozu.flywheel.core.model.ShadeSeparatingVertexConsumer.vertex(ShadeSeparatingVertexConsumer.java:42)

	Veil (veil), Version: 1.0.0
		Issue tracker URL: https://github.com/FoundryMC/Veil/issues
		at TRANSFORMER/veil@1.0.0/foundry.veil.impl.client.render.deferred.DeferredVertexConsumer.vertex(DeferredVertexConsumer.java:20)

	Create (create), Version: 0.5.1.j
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@0.5.1.j/com.simibubi.create.content.kinetics.base.HalfShaftInstance.getModel(HalfShaftInstance.java:19)
		
		
I'm not very experienced with Minecraft modding yet, so I was wondering if there was a way to isolate both libraries so that they don't interfere with each other or perhaps I'm simply making a mistake with my configuration? I'm honestly not sure.

**Comment by Ocelot5836** [comment]
Fixed in 1.21
